numeros = list(map(int, input("Digite uma lista de números inteiros separados por espaço: ").split()))
maior = max(numeros)
menor = min(numeros)
print("O maior número é:", maior)
print("O menor número é:", menor)
